const ENGLISH_NAME_TYPE = "plain-language translations";

const FAMILY_ORDER = [
  {
    key: "conifer-forest",
    name: "Conifer forest",
    legendSection: "natural",
  },
  {
    key: "mixed-conifer-broadleaf-forest",
    name: "Mixed conifer–broadleaf forest",
    legendSection: "natural",
  },
  {
    key: "broadleaf-forest",
    name: "Broadleaf forest",
    legendSection: "natural",
  },
  {
    key: "shrubland",
    name: "Shrubland",
    legendSection: "natural",
  },
  {
    key: "grass-herbaceous",
    name: "Grass / herbaceous vegetation",
    legendSection: "natural",
  },
  {
    key: "rock-scree-cliff",
    name: "Rock / scree / cliff vegetation",
    legendSection: "natural",
  },
  {
    key: "coastal-vegetation",
    name: "Coastal vegetation",
    legendSection: "natural",
  },
  {
    key: "bamboo",
    name: "Bamboo",
    legendSection: "natural",
  },
  {
    key: "human-modified-land",
    name: "Human-modified land",
    legendSection: "other",
  },
  {
    key: "other-source-classes",
    name: "Other source classes",
    legendSection: "other",
  },
];

const FAMILY_MAP = Object.fromEntries(FAMILY_ORDER.map((family) => [family.key, family]));

const CLASSES = [
  {
    code: 12,
    officialName: "亞高山針葉林",
    englishName: "Subalpine conifer forest",
    familyKey: "conifer-forest",
    natural: true,
    color: "#2f6f44",
    derivedAltitudinalZone: "Subalpine",
  },
  {
    code: 13,
    officialName: "上部山地針葉林",
    englishName: "Upper-montane conifer forest",
    familyKey: "conifer-forest",
    natural: true,
    color: "#2f6f44",
    derivedAltitudinalZone: "Upper montane",
  },
  {
    code: 14,
    officialName: "上部山地－山地－下部山地次生針葉林",
    englishName: "Upper- to lower-montane secondary conifer forest",
    familyKey: "conifer-forest",
    natural: true,
    color: "#2f6f44",
    derivedAltitudinalZone: "Upper montane to lower montane",
  },
  {
    code: 15,
    officialName: "山地針葉林",
    englishName: "Montane conifer forest",
    familyKey: "conifer-forest",
    natural: true,
    color: "#2f6f44",
    derivedAltitudinalZone: "Montane",
  },
  {
    code: 16,
    officialName: "上部山地針闊葉混淆林",
    englishName: "Upper-montane mixed conifer–broadleaf forest",
    familyKey: "mixed-conifer-broadleaf-forest",
    natural: true,
    color: "#5d8f4a",
    derivedAltitudinalZone: "Upper montane",
  },
  {
    code: 17,
    officialName: "上部山地－山地－下部山地針闊葉次生混淆林",
    englishName: "Upper- to lower-montane secondary mixed conifer–broadleaf forest",
    familyKey: "mixed-conifer-broadleaf-forest",
    natural: true,
    color: "#5d8f4a",
    derivedAltitudinalZone: "Upper montane to lower montane",
  },
  {
    code: 18,
    officialName: "山地針闊葉混淆林",
    englishName: "Montane mixed conifer–broadleaf forest",
    familyKey: "mixed-conifer-broadleaf-forest",
    natural: true,
    color: "#5d8f4a",
    derivedAltitudinalZone: "Montane",
  },
  {
    code: 19,
    officialName: "下部山地針闊葉混淆林",
    englishName: "Lower-montane mixed conifer–broadleaf forest",
    familyKey: "mixed-conifer-broadleaf-forest",
    natural: true,
    color: "#5d8f4a",
    derivedAltitudinalZone: "Lower montane",
  },
  {
    code: 20,
    officialName: "上部山地－山地－下部山地崩塌地次生落葉闊葉林",
    englishName: "Upper- to lower-montane landslide secondary deciduous broadleaf forest",
    familyKey: "broadleaf-forest",
    natural: true,
    color: "#5aa053",
    derivedAltitudinalZone: "Upper montane to lower montane",
  },
  {
    code: 21,
    officialName: "山地常綠闊葉林",
    englishName: "Montane evergreen broadleaf forest",
    familyKey: "broadleaf-forest",
    natural: true,
    color: "#5aa053",
    derivedAltitudinalZone: "Montane",
  },
  {
    code: 22,
    officialName: "山地常綠闊葉矮林",
    englishName: "Montane evergreen broadleaf dwarf forest",
    familyKey: "broadleaf-forest",
    natural: true,
    color: "#5aa053",
    derivedAltitudinalZone: "Montane",
  },
  {
    code: 23,
    officialName: "山地落葉闊葉林",
    englishName: "Montane deciduous broadleaf forest",
    familyKey: "broadleaf-forest",
    natural: true,
    color: "#5aa053",
    derivedAltitudinalZone: "Montane",
  },
  {
    code: 24,
    officialName: "山地－下部山地－低地次生落葉闊葉林",
    englishName: "Montane to lowland secondary deciduous broadleaf forest",
    familyKey: "broadleaf-forest",
    natural: true,
    color: "#5aa053",
    derivedAltitudinalZone: "Montane to lowland",
  },
  {
    code: 25,
    officialName: "山地－下部山地－低地半落葉闊葉林",
    englishName: "Montane to lowland semi-deciduous broadleaf forest",
    familyKey: "broadleaf-forest",
    natural: true,
    color: "#5aa053",
    derivedAltitudinalZone: "Montane to lowland",
  },
  {
    code: 26,
    officialName: "下部山地常綠闊葉林",
    englishName: "Lower-montane evergreen broadleaf forest",
    familyKey: "broadleaf-forest",
    natural: true,
    color: "#5aa053",
    derivedAltitudinalZone: "Lower montane",
  },
  {
    code: 27,
    officialName: "下部山地－低地次生常綠闊葉林",
    englishName: "Lower-montane to lowland secondary evergreen broadleaf forest",
    familyKey: "broadleaf-forest",
    natural: true,
    color: "#5aa053",
    derivedAltitudinalZone: "Lower montane to lowland",
  },
  {
    code: 28,
    officialName: "低地常綠闊葉林",
    englishName: "Lowland evergreen broadleaf forest",
    familyKey: "broadleaf-forest",
    natural: true,
    color: "#5aa053",
    derivedAltitudinalZone: "Lowland",
  },
  {
    code: 29,
    officialName: "低地風衝常綠闊葉矮林",
    englishName: "Wind-pruned lowland evergreen broadleaf dwarf forest",
    familyKey: "broadleaf-forest",
    natural: true,
    color: "#5aa053",
    derivedAltitudinalZone: "Lowland",
  },
  {
    code: 30,
    officialName: "竹林",
    englishName: "Bamboo forest",
    familyKey: "bamboo",
    natural: true,
    color: "#7bbf59",
    derivedAltitudinalZone: "Not specified in the class name",
  },
  {
    code: 31,
    officialName: "熱帶海岸林",
    englishName: "Tropical coastal forest",
    familyKey: "coastal-vegetation",
    natural: true,
    color: "#4a8d4d",
    derivedAltitudinalZone: "Coastal",
  },
  {
    code: 32,
    officialName: "高山針闊葉灌叢",
    englishName: "Alpine conifer–broadleaf shrubland",
    familyKey: "shrubland",
    natural: true,
    color: "#c68d2d",
    derivedAltitudinalZone: "Alpine",
  },
  {
    code: 33,
    officialName: "亞高山－上部山地－山地針闊葉灌叢",
    englishName: "Subalpine to montane conifer–broadleaf shrubland",
    familyKey: "shrubland",
    natural: true,
    color: "#c68d2d",
    derivedAltitudinalZone: "Subalpine to montane",
  },
  {
    code: 34,
    officialName: "下部山地－低地闊葉灌叢",
    englishName: "Lower-montane to lowland broadleaf shrubland",
    familyKey: "shrubland",
    natural: true,
    color: "#c68d2d",
    derivedAltitudinalZone: "Lower montane to lowland",
  },
  {
    code: 35,
    officialName: "海岸闊葉灌叢",
    englishName: "Coastal broadleaf shrubland",
    familyKey: "coastal-vegetation",
    natural: true,
    color: "#c68d2d",
    derivedAltitudinalZone: "Coastal",
  },
  {
    code: 36,
    officialName: "高山草本植群",
    englishName: "Alpine herbaceous vegetation",
    familyKey: "grass-herbaceous",
    natural: true,
    color: "#d9d96b",
    derivedAltitudinalZone: "Alpine",
  },
  {
    code: 37,
    officialName: "亞高山－上部山地－山地草本植群",
    englishName: "Subalpine to montane herbaceous vegetation",
    familyKey: "grass-herbaceous",
    natural: true,
    color: "#d9d96b",
    derivedAltitudinalZone: "Subalpine to montane",
  },
  {
    code: 38,
    officialName: "下部山地－低地草本植群",
    englishName: "Lower-montane to lowland herbaceous vegetation",
    familyKey: "grass-herbaceous",
    natural: true,
    color: "#d9d96b",
    derivedAltitudinalZone: "Lower montane to lowland",
  },
  {
    code: 39,
    officialName: "砂丘植群",
    englishName: "Dune vegetation",
    familyKey: "coastal-vegetation",
    natural: true,
    color: "#4a8d4d",
    derivedAltitudinalZone: "Coastal",
  },
  {
    code: 40,
    officialName: "亞高山－上部山地－山地岩壁及碎石坡植群",
    englishName: "Subalpine to montane cliff and scree vegetation",
    familyKey: "rock-scree-cliff",
    natural: true,
    color: "#8f8475",
    derivedAltitudinalZone: "Subalpine to montane",
  },
  {
    code: 41,
    officialName: "下部山地－低地岩壁及碎石坡植群",
    englishName: "Lower-montane to lowland cliff and scree vegetation",
    familyKey: "rock-scree-cliff",
    natural: true,
    color: "#8f8475",
    derivedAltitudinalZone: "Lower montane to lowland",
  },
  {
    code: 42,
    officialName: "海岸岩壁植群",
    englishName: "Coastal cliff vegetation",
    familyKey: "coastal-vegetation",
    natural: true,
    color: "#8f8475",
    derivedAltitudinalZone: "Coastal",
  },
  {
    code: 43,
    officialName: "人工林",
    englishName: "Plantation forest",
    familyKey: "human-modified-land",
    natural: false,
    color: "#3f8f71",
    derivedAltitudinalZone: "Not specified in the class name",
  },
  {
    code: 44,
    officialName: "耕地",
    englishName: "Cropland",
    familyKey: "human-modified-land",
    natural: false,
    color: "#c6a766",
    derivedAltitudinalZone: "Not specified in the class name",
  },
  {
    code: 45,
    officialName: "建地",
    englishName: "Built land",
    familyKey: "human-modified-land",
    natural: false,
    color: "#676d73",
    derivedAltitudinalZone: "Not specified in the class name",
  },
  {
    code: 46,
    officialName: "天然裸露地",
    englishName: "Natural bare land",
    familyKey: "other-source-classes",
    natural: true,
    color: "#9f8c6f",
    derivedAltitudinalZone: "Not specified in the class name",
  },
  {
    code: 47,
    officialName: "水域",
    englishName: "Water",
    familyKey: "other-source-classes",
    natural: true,
    color: "#4f7cff",
    derivedAltitudinalZone: "Not specified in the class name",
  },
  {
    code: 48,
    officialName: "公園、墓地",
    englishName: "Parks and cemeteries",
    familyKey: "human-modified-land",
    natural: false,
    color: "#4a8d4d",
    derivedAltitudinalZone: "Not specified in the class name",
  },
  {
    code: 49,
    officialName: "人工裸露地",
    englishName: "Artificial bare land",
    familyKey: "human-modified-land",
    natural: false,
    color: "#9f8c6f",
    derivedAltitudinalZone: "Not specified in the class name",
  },
].map((item) => ({
  ...item,
  family: FAMILY_MAP[item.familyKey].name,
}));

const SECTION_META = {
  natural: {
    key: "natural",
    title: "Natural ecosystems",
    description: "Primary vegetation and ecosystem classes for ecological exploration and travel.",
  },
  other: {
    key: "other",
    title: "Other source classes",
    description: "Source classes kept for context, including human-modified land and non-vegetation categories.",
  },
};

const sections = Object.values(SECTION_META).map((section) => ({
  ...section,
  families: FAMILY_ORDER.filter((family) => family.legendSection === section.key).map((family) => ({
    ...family,
    classes: CLASSES.filter((item) => item.familyKey === family.key),
  })).filter((family) => family.classes.length > 0),
}));

module.exports = {
  englishNameType: ENGLISH_NAME_TYPE,
  families: FAMILY_ORDER,
  classes: CLASSES,
  sections,
};
